views/city.py
from flask import Flask, redirect, url_for, render_template, request, flash, Blueprint
from models import db, City, Country, Countrylanguage
from forms import CityForm
import logging
from humanize import intcomma

app_city = Blueprint('city', 'city', url_prefix='/city')

# Pagination
PER_PAGE = 20


@app_city.route("/", methods=['GET'], defaults={'_route': 'list_cities'})
@app_city.route("/<int:page>", methods=['GET'], defaults={'_route': 'list_cities'})
def cities(_route, page=1):
    '''
    All cities
    '''
    sort_by = None
    if request.args.get('sort_by', '') in ['name', 'countrycode', 'district', 'population']:
        sort_by = 'City.{}'.format(request.args.get('sort_by'))

    # if sort_by is not None:
    #     sort_by = sort_by[1:] if sort_by.startswith('-') else '-'+sort_by
        # request.args.set('sort_by', sort_by)

    cities = db.session.query(City, Country).outerjoin(
        Country, City.countrycode==Country.code).order_by(
        sort_by).paginate(page, PER_PAGE, error_out=False)
    return render_template('web/cities.html', cities=cities, intcomma=intcomma, _route=_route)

@app_city.route("/search", defaults={'_route': 'search_cities'})
@app_city.route("/search/<int:page>", defaults={'_route': 'search_cities'})
def search_city(_route, page=1):
    '''
    Search city
    '''
    city_search = request.args.get('name')
    city_search_type = request.args.get('type')

    args = []
    if city_search_type == 'name':
        args.append(City.name.contains(city_search))
    elif city_search_type == 'countrycode':
        city_search = city_search.upper()
        args.append(City.countrycode.contains(city_search))
    elif city_search_type == 'district':
        args.append(City.district.contains(city_search))

    sort_by = 'City.name'
    if request.args.get('sort_by', '') in ['name', 'countrycode', 'district', 'population']:
        sort_by = 'City.{}'.format(request.args.get('sort_by'))

    direction = ''
    if request.args.get('dir', '') in ['asc', 'desc']:
        direction = '' if request.args.get('dir')=='asc' else 'desc'

    all_cities = db.session.query(City, Country).outerjoin(
        Country, City.countrycode==Country.code).filter(
        *args).order_by(
        "{} {}".format(sort_by, direction)).paginate(
        page, PER_PAGE, error_out=False)
    return render_template('web/cities.html', cities=all_cities, intcomma=intcomma, _route=_route)

@app_city.route("/create", methods=('GET', 'POST'))
def create_city():
    '''
    Create city
    '''
    form = CityForm()
    if form.validate_on_submit():
        city = City()
        form.populate_obj(city)
        db.session.add(city)
        try:
            db.session.commit()
            flash('City created correctly', 'success')
            return redirect(url_for('city.cities', **request.args))
        except Exception as e:
            db.session.rollback()
            flash('Error creating city', 'danger')

    return render_template('web/create_city.html', form=form)

@app_city.route("/delete", methods=('POST',))
def delete_city():
    '''
    Delete city
    '''
    try:
        city = City.query.filter_by(id=request.form['id']).first()
        db.session.delete(city)
        db.session.commit()
        flash('Delete successfully.', 'danger')
    except Exception as e:
        logging.error(e, exc_info=True)
        db.session.rollback()
        flash('Error deleting city.', 'danger')

    return redirect(url_for('city.search_city', **request.args))


@app_city.route("/edit/<int:id>", methods=('GET', 'POST'))
def edit_city(id):
    '''
    Edit City
    '''
    city = City.query.filter_by(id=id).first()
    form = CityForm(obj=city)
    if form.validate_on_submit():
        try:
            form.populate_obj(city)
            db.session.add(city)
            db.session.commit()
            flash('Saved successfully', 'success')
        except:
            db.session.rollback()
            flash('Error updating city.', 'danger')
    return render_template(
        'web/edit_city.html',
        form=form)

views/country.py
from flask import Flask, redirect, url_for, render_template, request, flash, Blueprint
from models import db, City, Country, Countrylanguage
from forms import CountryForm
import logging
from humanize import intcomma

app_country = Blueprint('country', 'country', url_prefix='/country')

# Pagination
PER_PAGE = 20


@app_country.route("/", methods=['GET'], defaults={'_route': 'list_country'})
@app_country.route("/<int:page>", methods=['GET'], defaults={'_route': 'list_country'})
def country(_route, page=1):
    '''
    All Coutries
    '''
    sort_by = 'name'
    if request.args.get('sort_by', '') in ['name', 'code', 'continent', 'population', 'region']:
        sort_by = request.args.get('sort_by')

    countries = db.session.query(Country).order_by(
        sort_by).paginate(page, PER_PAGE, error_out=False)
    return render_template('web/countries.html', countries=countries, intcomma=intcomma, _route=_route)

@app_country.route("/search", defaults={'_route': 'search_country'})
@app_country.route("/search/<int:page>", defaults={'_route': 'search_country'})
def search_country(_route, page=1):
    '''
    Search country
    '''
    country_search = request.args.get('name', '')
    country_search_type = request.args.get('type', '')

    args = []
    if country_search_type in ['name']:
        args.append(Country.name.contains(country_search))
    elif country_search_type in ['code']:
        args.append(Country.code.contains(country_search))
    elif country_search_type in ['continent']:
        args.append(Country.continent.contains(country_search))
    elif country_search_type in ['population']:
        args.append(Country.population.contains(country_search))
    elif country_search_type in ['region']:
        args.append(Country.region.contains(country_search))

    sort_by = 'name'
    if request.args.get('sort_by', '') in ['name', 'code', 'continent', 'population', 'region']:
        sort_by = request.args.get('sort_by')

    direction = ''
    if request.args.get('dir', '') in ['asc', 'desc']:
        direction = '' if request.args.get('dir')=='asc' else 'desc'

    all_countries = db.session.query(Country).filter(
        *args).order_by("{} {}".format(sort_by, direction)
        ).paginate(
        page, PER_PAGE, error_out=False)
    return render_template('web/countries.html', countries=all_countries, intcomma=intcomma, _route=_route)

@app_country.route("/create", methods=('GET', 'POST'))
def create_country():
    '''
    Create Country
    '''
    form = CountryForm()
    form.capital.choices += [(i.id, i.name) for i in db.session.query(City).order_by(City.name).all()]

    if form.validate_on_submit():
        country = Country()
        form.populate_obj(country)
        db.session.add(country)
        try:
            db.session.commit()
            flash('City created correctly', 'success')
            return redirect(url_for('country.country', **request.args))
        except Exception as e:
            db.session.rollback()
            flash('Error creating country', 'danger')

    return render_template('web/create_country.html', form=form)

@app_country.route("/delete", methods=('POST',))
def delete_country():
    '''
    Delete country
    '''
    try:
        country = Country.query.filter_by(id=request.form['id']).first()
        db.session.delete(country)
        db.session.commit()
        flash('Delete successfully.', 'danger')
    except Exception as e:
        logging.error(e, exc_info=True)
        db.session.rollback()
        flash('Error deleting country.', 'danger')

    return redirect(url_for('country.search_country', **request.args))


@app_country.route("/edit/<int:id>", methods=('GET', 'POST'))
def edit_country(id):
    '''
    Edit Country
    '''
    country = Country.query.filter_by(id=id).first()
    form = CountryForm(obj=country)
    form.capital.choices += [(i.id, i.name) for i in db.session.query(City).order_by(City.name).all()]

    if form.validate_on_submit():
        try:
            form.populate_obj(country)
            db.session.add(country)
            db.session.commit()
            flash('Saved successfully', 'success')
        except:
            db.session.rollback()
            flash('Error updating country.', 'danger')
    return render_template(
        'web/edit_country.html',
        form=form)

templates/web/cities.html
{% extends 'layouts/base.html' %}
{% block title %}View{% endblock %}

{% block right_nav_bar %}
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<form action="{{ url_for('city.search_city') }}" method="get" class="navbar-form navbar-left">
	<div class="form-group">
	  <select class="form-control" name="type" required>
	  	<option {% if not request.args.type %}  selected="selected" {% endif %} value="" disabled>Search Kind</option>
	  	<option {% if request.args.type=='name' %} selected="selected" {% endif %} value="name">Name</option>
	  	<option {% if request.args.type=='countrycode' %} selected="selected" {% endif %} value="countrycode">Country Code</option>
	  	<option {% if request.args.type=='district' %} selected="selected" {% endif %} value="district">District</option>
	  </select>
	  <input type="text" name="name" class="form-control" placeholder="Query" value="{{request.args.name or ''}}">
	</div>
	<button type="submit" class="btn btn-default">Search</button>
  </form>
  <ul class="nav navbar-nav navbar-right">
	  <li><a href="{{ url_for('city.create_city') }}">New City</a></li>
	  <li><a href="{{ url_for('city.cities') }}">View cities</a></li>
  </ul>
</div>
{% endblock %}

{% block body %}
<h1>Cities</h1>
<table class="table table-hover">
	<thead>
		<tr>
			<th scope="col">
				Name
				<a href="{{ url_for('city.search_city', sort_by='name', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('city.search_city', sort_by='name', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>
			<th scope="col">
				Country
				<a href="{{ url_for('city.search_city', sort_by='countrycode', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('city.search_city', sort_by='countrycode', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>
			<th scope="col">
				Region
				<a href="{{ url_for('city.search_city', sort_by='region', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('city.search_city', sort_by='region', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>
			<th scope="col">
				District
				<a href="{{ url_for('city.search_city', sort_by='district', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('city.search_city', sort_by='district', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>
			<th scope="col">
				Population
				<a href="{{ url_for('city.search_city', sort_by='population', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('city.search_city', sort_by='population', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>			
			<td></td>
		</tr>
	</thead>
	<tbody>
	{% for city in cities.items %}
		<tr>
			<td>{{ city.City.name }}</td>
			<td>{{ city.Country.name }} ({{ city.City.countrycode }})</td>
			<td>{{ city.Country.region or 'NA' }}</td>
			<td>{{ city.City.district }}</td>
			<td>{{ intcomma(city.City.population) }}</td>
			<td class="text-right">
				<div class="row">
					<form action="{{ url_for('city.delete_city', **request.args) }}" method="post" class="pull-right">
						<input type="hidden" name="id" value="{{ city.City.id }}">
						<input type="submit" class="btn btn-danger" data-toggle="confirmation" value="Delete">
					</form>
					<a class="btn btn-primary pull-right" href="{{ url_for('city.edit_city', id=city.City.id) }}">Edit</a>
				</div>
			</td>
		</tr>
	{% endfor %}
	<tr>
		<td>{% if cities.has_prev %}<a class="btn btn-primary pull-left" href="
			{% if _route == 'list_cities' %}
			{{ url_for('city.cities', page=1, **request.args) }}
			{% elif _route == 'search_cities' %}
			{{ url_for('city.search_city', page=1, **request.args) }}
			{% endif %}
			">
			&lt;&lt; First Page</a>{% endif %}</td>
		<td>{% if cities.has_prev %}<a class="btn btn-primary pull-left" href="
			{% if _route == 'list_cities' %}
			{{ url_for('city.cities', page=cities.prev_num, **request.args) }}
			{% elif _route == 'search_cities' %}
			{{ url_for('city.search_city', page=cities.prev_num, **request.args) }}
			{% endif %}
			"
			>&lt; Prev Page</a>{% endif %}</td>
		<td></td>
		<td></td>
		<td>{% if cities.has_next %}<a class="btn btn-primary pull-right" href="
			{% if _route == 'list_cities' %}
			{{ url_for('city.cities', page=cities.next_num, **request.args) }}
			{% elif _route == 'search_cities' %}
			{{ url_for('city.search_city', page=cities.next_num, **request.args) }}
			{% endif %}
			">Next Page &gt;</a>{% endif %}</td>
		<td>{% if cities.has_next %}<a class="btn btn-primary pull-right" href="
			{% if _route == 'list_cities' %}
			{{ url_for('city.cities', page=cities.pages, **request.args) }}
			{% elif _route == 'search_cities' %}
			{{ url_for('city.search_city', page=cities.pages, **request.args) }}
			{% endif %}
			">Last Page &gt;&gt;</a>{% endif %}</td>
	</tr>
	</tbody>
</table>


{% endblock %}

templates/web/countries.html
{% extends 'layouts/base.html' %}
{% block title %}View{% endblock %}

{% block right_nav_bar %}
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<form action="{{ url_for('country.search_country') }}" method="get" class="navbar-form navbar-left">
	<div class="form-group">
	  <select class="form-control" name="type" required>
	  	<option {% if not request.args.type %}  selected="selected" {% endif %} value="" disabled>Search Kind</option>
	  	<option {% if request.args.type=='name' %} selected="selected" {% endif %} value="name">Name</option>
	  	<option {% if request.args.type=='code' %} selected="selected" {% endif %} value="code">Country Code</option>
	  	<option {% if request.args.type=='region' %} selected="selected" {% endif %} value="region">Region</option>
	  	<option {% if request.args.type=='continent' %} selected="selected" {% endif %} value="continent">Continent</option>
	  </select>
	  <input type="text" name="name" class="form-control" placeholder="Query" value="{{request.args.name or ''}}">
	</div>
	<button type="submit" class="btn btn-default">Search</button>
  </form>
  <ul class="nav navbar-nav navbar-right">
	  <li><a href="{{ url_for('country.create_country') }}">New Country</a></li>
	  <li><a href="{{ url_for('country.country') }}">View Countries</a></li>
  </ul>
</div>
{% endblock %}

{% block body %}
<h1>Countries</h1>
<table class="table table-hover">
	<thead>
		<tr>
			<th scope="col">
				Name
				<a href="{{ url_for('country.search_country', sort_by='name', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('country.search_country', sort_by='name', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>
			<th scope="col">
				Code
				<a href="{{ url_for('country.search_country', sort_by='code', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('country.search_country', sort_by='code', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>
			<th scope="col">
				Region
				<a href="{{ url_for('country.search_country', sort_by='region', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('country.search_country', sort_by='region', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>
			<th scope="col">
				Continent
				<a href="{{ url_for('country.search_country', sort_by='continent', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('country.search_country', sort_by='continent', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>
			<th scope="col">
				Population
				<a href="{{ url_for('country.search_country', sort_by='population', dir='asc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-down"></i>
				</a>
				<a href="{{ url_for('country.search_country', sort_by='population', dir='desc', type=request.args.type, name=request.args.name) }}">
					<i class="fas fa-sort-alpha-up"></i>
				</a>
			</th>
			<td></td>
		</tr>
	</thead>
	<tbody>
	{% for country in countries.items %}
		<tr>
			<td>{{ country.name }}</td>
			<td>{{ country.code }}</td>
			<td>{{ country.region}}</td>
			<td>{{ country.continent }}</td>
			<td>{{ intcomma(country.population) }}</td>
			<td class="text-right">
				<div class="row">
					<form action="{{ url_for('country.delete_country', **request.args) }}" method="post" class="pull-right">
						<input type="hidden" name="id" value="{{ country.id }}">
						<input type="submit" class="btn btn-danger" data-toggle="confirmation" value="Delete">
					</form>
					<a class="btn btn-primary pull-right" href="{{ url_for('country.edit_country', id=country.id) }}">Edit</a>
				</div>
			</td>
		</tr>
	{% endfor %}
	<tr>
		<td>{% if countries.has_prev %}<a class="btn btn-primary pull-left" href="
			{% if _route == 'list_country' %}
			{{ url_for('country.country', page=1, **request.args) }}
			{% elif _route == 'search_country' %}
			{{ url_for('country.search_country', page=1, **request.args) }}
			{% endif %}
			">
			&lt;&lt; First Page</a>{% endif %}</td>
		<td>{% if countries.has_prev %}<a class="btn btn-primary pull-left" href="
			{% if _route == 'list_country' %}
			{{ url_for('country.country', page=countries.prev_num, **request.args) }}
			{% elif _route == 'search_country' %}
			{{ url_for('country.search_country', page=countries.prev_num, **request.args) }}
			{% endif %}
			"
			>&lt; Prev Page</a>{% endif %}</td>
		<td></td>
		<td></td>
		<td>{% if countries.has_next %}<a class="btn btn-primary pull-right" href="
			{% if _route == 'list_country' %}
			{{ url_for('country.country', page=countries.next_num, **request.args) }}
			{% elif _route == 'search_country' %}
			{{ url_for('country.search_country', page=countries.next_num, **request.args) }}
			{% endif %}
			">Next Page &gt;</a>{% endif %}</td>
		<td>{% if countries.has_next %}<a class="btn btn-primary pull-right" href="
			{% if _route == 'list_country' %}
			{{ url_for('country.country', page=countries.pages, **request.args) }}
			{% elif _route == 'search_country' %}
			{{ url_for('country.search_country', page=countries.pages, **request.args) }}
			{% endif %}
			">Last Page &gt;&gt;</a>{% endif %}</td>
	</tr>
	</tbody>
</table>


{% endblock %}

templates/web/create_city.html
{% extends 'layouts/base.html' %}
{% block title %}New city{% endblock %}
{% block body %}
<h1>New city</h1>
<form method="post">
	{{ generate_fields(form) }}
	<input type="submit" class="btn btn-success" value="Add">
</form>
{% endblock %}

templates/web/create_country.html
{% extends 'layouts/base.html' %}
{% block title %}New Country{% endblock %}
{% block body %}
<h1>New country</h1>
<form method="post">
	{{ generate_fields(form) }}
	<input type="submit" class="btn btn-success" value="Add">
</form>
{% endblock %}

templates/web/edit_city.html
{% extends 'layouts/base.html' %}
{% block title %}Edit city{% endblock %}
{% block body %}
<h1>Edit city</h1>
<form method="post">
	{{ generate_fields(form) }}
	<input type="submit" class="btn btn-success" value="Save">
</form>
{% endblock %}

templates/web/edit_country.html
{% extends 'layouts/base.html' %}
{% block title %}Edit Country{% endblock %}
{% block body %}
<h1>Edit country</h1>
<form method="post">
	{{ generate_fields(form) }}
	<input type="submit" class="btn btn-success" value="Save">
</form>
{% endblock %}